name = "EGGO"
uuid = "25cd7528-e4e3-46fe-8df7-7ec8e1454e14"
authors = ["Joseph McClenaghan"]
version = "2.5.1"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
IMAS = "13ead8c1-b7d1-41bb-a6d0-5b8b65ed587a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PolygonOps = "647866c9-e3ac-4575-94e7-e3d426903924"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RegularizedLeastSquares = "1e9c538a-f78c-5de5-8ffb-0b6dbe892d23"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
VacuumFields = "9d9223b5-c5da-4bf4-abee-2a8bb6775a49"

[compat]
BSON = "0.3.9"
Flux = "0.14, 0.15, 0.16"
HDF5 = "0.17.2"
IMAS = "3, 4, 5, 6, 7"
Interpolations = "0.15.1, 0.16.1"
LinearAlgebra = "1.11.0"
PolygonOps = "0.1.2"
Random = "1.11.0"
RegularizedLeastSquares = "0.16.7"
Statistics = "1.11.1"
StatsBase = "0.34.5"
VacuumFields = "6"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
